# Generated by Django 3.1.3 on 2020-12-01 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Francelance',
            new_name='Freelance',
        ),
    ]
